### y = 2*XTX,通过反向传播计算y关于x每个分量的梯度

In [9]:
import torch

x = torch.arange(4.0 , requires_grad = True)
y = 2 * torch.dot(x,x)
x,y

(tensor([0., 1., 2., 3.], requires_grad=True),
 tensor(28., grad_fn=<MulBackward0>))

In [10]:
y.backward()
x.grad,x.grad==4*x

(tensor([ 0.,  4.,  8., 12.]), tensor([True, True, True, True]))

In [11]:
# 默认情况下，pyTorch会累计梯度，我们需要清楚之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [12]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数。一般用不到，要先sum转成标量再求梯度
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [13]:
#将某些计算移动到记录的计算图之外
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [14]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [18]:
# 构建函数的计算图需要通过Python控制流（例如，条件、循环或任意函数调用），仍然可以计算得到的变量的梯度。
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else :
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad == d / a

tensor(True)